In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"C:\Advait\VS_Code\Data Analysis\Tennis Data\atp_tennis.csv")

In [4]:
df.head()

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Arthurs W.,Gambill J.M.,Gambill J.M.,105,58,-1,-1,-1.0,-1.0,6-3 6-7 4-6
1,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Balcells J.,Henman T.,Henman T.,218,11,-1,-1,-1.0,-1.0,4-6 6-7
2,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Clement A.,Enqvist T.,Enqvist T.,56,5,-1,-1,-1.0,-1.0,3-6 3-6
3,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,63,77,-1,-1,-1.0,-1.0,6-4 6-2
4,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Draper S.,Norman M.,Norman M.,155,15,-1,-1,-1.0,-1.0,4-6 4-6

In [5]:
df.describe()

,Best of,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2
count,68591.000000,68591.000000,68591.000000,68591.000000,68591.000000,68591.000000,68591.000000
mean,3.377455,75.821784,75.405009,1144.813576,1151.906475,2.422549,2.414795
std,0.782590,100.216364,100.632302,1728.781762,1748.344357,2.678177,2.639873
min,3.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,3.000000,25.000000,24.000000,159.000000,160.000000,1.360000,1.350500
50%,3.000000,54.000000,54.000000,709.000000,710.000000,1.770000,1.800000
75%,3.000000,92.000000,92.000000,1260.000000,1265.000000,2.750000,2.750000
max,5.000000,3390.000000,4915.000000,16950.000000,16950.000000,67.000000,51.000000

In [6]:
cols_with_minus_one = ["Pts_1",	"Pts_2", "Odd_1", "Odd_2"]
df[cols_with_minus_one] = df[cols_with_minus_one].replace(-1, np.nan)

In [7]:
df.isna().sum()

Tournament        0
Date              0
Series            0
Court             0
Surface           0
Round             0
Best of           0
Player_1          0
Player_2          0
Winner            0
Rank_1            0
Rank_2            0
Pts_1         15652
Pts_2         15653
Odd_1          3782
Odd_2          3780
Score             0
dtype: int64

In [8]:
df["Date"] = pd.to_datetime(df["Date"])

In [9]:
df["Date"].dt.year.unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
       2022, 2023, 2024, 2025, 2026], dtype=int32)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 68591 entries, 0 to 68590
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tournament  68591 non-null  str
 1   Date        68591 non-null  datetime64[us]
 2   Series      68591 non-null  str
 3   Court       68591 non-null  str
 4   Surface     68591 non-null  str
 5   Round       68591 non-null  str
 6   Best of     68591 non-null  int64
 7   Player_1    68591 non-null  str
 8   Player_2    68591 non-null  str
 9   Winner      68591 non-null  str
 10  Rank_1      68591 non-null  int64
 11  Rank_2      68591 non-null  int64
 12  Pts_1       52939 non-null  float64
 13  Pts_2       52938 non-null  float64
 14  Odd_1       64809 non-null  float64
 15  Odd_2       64811 non-null  float64
 16  Score       68591 non-null  str
dtypes: datetime64[us](1), float64(4), int64(3), str(9)
memory usage: 8.9 MB

In [11]:
df["Year"] = df["Date"].dt.year

In [12]:
year_with_most_nan = df[cols_with_minus_one].isna().groupby(df["Year"], as_index=False).sum()
year_with_most_nan

    Year  Pts_1  Pts_2  Odd_1  Odd_2
0   2000   2874   2874   2874   2874
1   2001   2979   2979    448    448
2   2002   2700   2700    159    159
3   2003   2698   2698     52     52
4   2004   2782   2782     66     65
5   2005   1619   1619     21     21
6   2006      0      1     42     42
7   2007      0      0     38     37
8   2008      0      0     25     25
9   2009      0      0     18     18
10  2010      0      0     10     10
11  2011      0      0      7      7
12  2012      0      0      2      2
13  2013      0      0      1      1
14  2014      0      0      1      1
15  2015      0      0      2      2
16  2016      0      0      2      2
17  2017      0      0      3      3
18  2018      0      0      1      1
19  2019      0      0      1      1
20  2020      0      0      0      0
21  2021      0      0      0      0
22  2022      0      0      3      3
23  2023      0      0      2      2
24  2024      0      0      4      4
25  2025      0      0      0      0
26  2026      0      0      0      0

In [25]:
from rich.console import Console
console = Console()
from rich.pretty import Pretty
from rich.panel import Panel
from rich.table import Table

def show(text):
    console.print(Panel(Pretty(text)))

def EDA(train):
    datasets = {
        "train": train
    }
    table = Table(title="Dataset Summary", show_header=True, header_style="bold magenta")
    table.add_column("Dataset", style="cyan", justify="left")
    table.add_column("Rows", style="green", justify="right")
    table.add_column("Columns", style="yellow", justify="right")

    for name, df in datasets.items():

        #Dataset Summary

        table.add_row(
            name.upper(),
            str(len(df)),
            str(len(df.columns))
        )

        # Missing Value
        missing = df.isna().sum()
        total_missing = missing.sum()

        if total_missing == 0:
            show(text=f"{name} dataset -> No Missing Value")
        else:
            show(text=f"{name} missing")
            missing_df = missing[missing > 0].reset_index()
            missing_df.columns = ['Column', 'Missing Count']
            missing_df['% Missing'] = (missing_df['Missing Count'] / len(df) * 100).round(2)
            show(["⚠️ Missing Values", f"Всего пропусков: {total_missing} ({total_missing/df.size*100:.2f}% всех ячеек)"])
            show(missing_df)
            

    console.print(table)

In [26]:
EDA(df)

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 'train missing'                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ['⚠️ Missing Values', 'Всего пропусков: 38867 (3.15% всех ячеек)']                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│   Column  Missing Count  % Missing                                                                              │
│ 0  Pts_1          15652      22.82                                                                              │
│ 1  Pts_2          15653      22.82                                                                              │
│ 2  Odd_1           3782       5.51                                                                              │
│ 3  Odd_2           3780       5.51                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

       Dataset Summary
┏━━━━━━━━━┳━━━━━━━┳━━━━━━━━━┓
┃ Dataset ┃  Rows ┃ Columns ┃
┡━━━━━━━━━╇━━━━━━━╇━━━━━━━━━┩
│ TRAIN   │ 68591 │      18 │
└─────────┴───────┴─────────┘

In [59]:
df = df[df["Year"] >= 2009]

In [60]:
year_with_most_nan = df[cols_with_minus_one].isna().groupby(df["Year"], as_index=False).sum()
year_with_most_nan

    Year  Pts_1  Pts_2  Odd_1  Odd_2
0   2009      0      0     18     18
1   2010      0      0     10     10
2   2011      0      0      7      7
3   2012      0      0      2      2
4   2013      0      0      1      1
5   2014      0      0      1      1
6   2015      0      0      2      2
7   2016      0      0      2      2
8   2017      0      0      3      3
9   2018      0      0      1      1
10  2019      0      0      1      1
11  2020      0      0      0      0
12  2021      0      0      0      0
13  2022      0      0      3      3
14  2023      0      0      2      2
15  2024      0      0      4      4
16  2025      0      0      0      0
17  2026      0      0      0      0

In [66]:
df[cols_with_minus_one].isna().sum()

Pts_1     0
Pts_2     0
Odd_1    57
Odd_2    57
dtype: int64