In [99]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [122]:
from sklearn.preprocessing import OneHotEncoder

ModuleNotFoundError: No module named 'sklearn'

In [100]:
from pathlib import Path
data_path = Path(r"C:\Advait\VS_Code\Data Analysis\Tennis Data\jeff_sackmann\tennis_MatchChartingProject")

In [101]:
import tempfile
import os, glob
files = glob.glob(f"{data_path}/*.csv")
files

['C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-matches.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-points-2010s.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-points-2020s.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-points-to-2009.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-KeyPointsReturn.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-KeyPointsServe.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-NetPoints.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-Overview.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-Rally.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-ReturnDepth.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-ReturnOutcomes.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-ServeBasics.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-ServeDirection.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-ServeInfluence.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-ShotDirection.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-ShotDirOutcomes.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-ShotTypes.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-SnV.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-SvBreakSplit.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-m-stats-SvBreakTotal.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-matches.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-points-2010s.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-points-2020s.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-points-to-2009.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-KeyPointsReturn.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-KeyPointsServe.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-NetPoints.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-Overview.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-Rally.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-ReturnDepth.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-ReturnOutcomes.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-ServeBasics.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-ServeDirection.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-ServeInfluence.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-ShotDirection.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-ShotDirOutcomes.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-ShotTypes.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-SnV.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-SvBreakSplit.csv',
 'C:\\Advait\\VS_Code\\Data Analysis\\Tennis Data\\jeff_sackmann\\tennis_MatchChartingProject\\charting-w-stats-SvBreakTotal.csv']

In [102]:
atp_data = pd.read_csv(r"C:\Advait\VS_Code\Data Analysis\Tennis Data\atp_tennis.csv")
atp_data.head()

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Arthurs W.,Gambill J.M.,Gambill J.M.,105,58,-1,-1,-1.0,-1.0,6-3 6-7 4-6
1,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Balcells J.,Henman T.,Henman T.,218,11,-1,-1,-1.0,-1.0,4-6 6-7
2,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Clement A.,Enqvist T.,Enqvist T.,56,5,-1,-1,-1.0,-1.0,3-6 3-6
3,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,63,77,-1,-1,-1.0,-1.0,6-4 6-2
4,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Draper S.,Norman M.,Norman M.,155,15,-1,-1,-1.0,-1.0,4-6 4-6

In [103]:
atp_data.describe()

,Best of,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2
count,68591.000000,68591.000000,68591.000000,68591.000000,68591.000000,68591.000000,68591.000000
mean,3.377455,75.821784,75.405009,1144.813576,1151.906475,2.422549,2.414795
std,0.782590,100.216364,100.632302,1728.781762,1748.344357,2.678177,2.639873
min,3.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,3.000000,25.000000,24.000000,159.000000,160.000000,1.360000,1.350500
50%,3.000000,54.000000,54.000000,709.000000,710.000000,1.770000,1.800000
75%,3.000000,92.000000,92.000000,1260.000000,1265.000000,2.750000,2.750000
max,5.000000,3390.000000,4915.000000,16950.000000,16950.000000,67.000000,51.000000

In [104]:
atp_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 68591 entries, 0 to 68590
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tournament  68591 non-null  str
 1   Date        68591 non-null  str
 2   Series      68591 non-null  str
 3   Court       68591 non-null  str
 4   Surface     68591 non-null  str
 5   Round       68591 non-null  str
 6   Best of     68591 non-null  int64
 7   Player_1    68591 non-null  str
 8   Player_2    68591 non-null  str
 9   Winner      68591 non-null  str
 10  Rank_1      68591 non-null  int64
 11  Rank_2      68591 non-null  int64
 12  Pts_1       68591 non-null  int64
 13  Pts_2       68591 non-null  int64
 14  Odd_1       68591 non-null  float64
 15  Odd_2       68591 non-null  float64
 16  Score       68591 non-null  str
dtypes: float64(2), int64(5), str(10)
memory usage: 8.9 MB

In [105]:
# the data are of the following years 2000 - 2026
pd.to_datetime(atp_data["Date"]).dt.year.unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
       2022, 2023, 2024, 2025, 2026], dtype=int32)

In [106]:
atp_data["Date"] =  pd.to_datetime(atp_data["Date"])

In [107]:
atp_data["Court"].unique(), atp_data["Surface"].unique()

(<StringArray>
 ['Outdoor', 'Indoor']
 Length: 2, dtype: str,
 <StringArray>
 ['Hard', 'Clay', 'Grass', 'Carpet']
 Length: 4, dtype: str)

In [108]:
atp_data.isna().sum()

Tournament    0
Date          0
Series        0
Court         0
Surface       0
Round         0
Best of       0
Player_1      0
Player_2      0
Winner        0
Rank_1        0
Rank_2        0
Pts_1         0
Pts_2         0
Odd_1         0
Odd_2         0
Score         0
dtype: int64

In [109]:
atp_data.duplicated().sum()

np.int64(0)

In [110]:
cols_with_minus1 = ["Rank_1", "Rank_2", "Pts_1", "Pts_2", "Odd_1", "Odd_2"]
atp_data[cols_with_minus1] = atp_data[cols_with_minus1].replace(-1, np.nan)

In [111]:
atp_data[cols_with_minus1].isna().groupby(atp_data["Date"].dt.year).sum()

      Rank_1  Rank_2  Pts_1  Pts_2  Odd_1  Odd_2
Date
2000       6       3   2874   2874   2874   2874
2001       6       4   2979   2979    448    448
2002       2       4   2700   2700    159    159
2003       0       1   2698   2698     52     52
2004       0       0   2782   2782     66     65
2005       0       0   1619   1619     21     21
2006       0       0      0      1     42     42
2007       0       0      0      0     38     37
2008       0       0      0      0     25     25
2009       0       0      0      0     18     18
2010       0       0      0      0     10     10
2011       0       0      0      0      7      7
2012       0       0      0      0      2      2
2013       0       0      0      0      1      1
2014       0       0      0      0      1      1
2015       0       0      0      0      2      2
2016       0       0      0      0      2      2
2017       0       0      0      0      3      3
2018       0       0      0      0      1      1
2019       0       0      0      0      1      1
2020       0       0      0      0      0      0
2021       0       0      0      0      0      0
2022       0       0      0      0      3      3
2023       0       0      0      0      2      2
2024       0       0      0      0      4      4
2025       0       0      0      0      0      0
2026       0       0      0      0      0      0

In [112]:
df = atp_data[atp_data["Date"].dt.year >= 2010]
df.head()

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
27525,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Bellucci T.,Chela J.I.,Bellucci T.,36.0,73.0,1021.0,611.0,1.61,2.20,6-3 3-6 6-1
27526,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Falla A.,Chardy J.,Falla A.,81.0,32.0,587.0,1102.0,2.62,1.44,6-4 6-4
27527,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Llodra M.,Levy H.,Levy H.,67.0,119.0,649.0,461.0,1.36,3.00,2-6 0-6
27528,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Millman J.,Stepanek R.,Stepanek R.,306.0,12.0,137.0,2625.0,10.00,1.04,4-6 0-6
27529,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Nieminen J.,Gasquet R.,Gasquet R.,88.0,52.0,568.0,850.0,2.62,1.44,3-6 6-4 4-6

In [113]:
df.isna().sum()

Tournament     0
Date           0
Series         0
Court          0
Surface        0
Round          0
Best of        0
Player_1       0
Player_2       0
Winner         0
Rank_1         0
Rank_2         0
Pts_1          0
Pts_2          0
Odd_1         39
Odd_2         39
Score          0
dtype: int64

In [114]:
df = df.dropna()

In [115]:
df.isna().sum()

Tournament    0
Date          0
Series        0
Court         0
Surface       0
Round         0
Best of       0
Player_1      0
Player_2      0
Winner        0
Rank_1        0
Rank_2        0
Pts_1         0
Pts_2         0
Odd_1         0
Odd_2         0
Score         0
dtype: int64

In [116]:
df.head(5)

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
27525,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Bellucci T.,Chela J.I.,Bellucci T.,36.0,73.0,1021.0,611.0,1.61,2.20,6-3 3-6 6-1
27526,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Falla A.,Chardy J.,Falla A.,81.0,32.0,587.0,1102.0,2.62,1.44,6-4 6-4
27527,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Llodra M.,Levy H.,Levy H.,67.0,119.0,649.0,461.0,1.36,3.00,2-6 0-6
27528,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Millman J.,Stepanek R.,Stepanek R.,306.0,12.0,137.0,2625.0,10.00,1.04,4-6 0-6
27529,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3,Nieminen J.,Gasquet R.,Gasquet R.,88.0,52.0,568.0,850.0,2.62,1.44,3-6 6-4 4-6

In [117]:
df["Round"].unique()

<StringArray>
[    '1st Round',     '2nd Round', 'Quarterfinals',    'Semifinals',
     'The Final',     '3rd Round',     '4th Round',   'Round Robin']
Length: 8, dtype: str

In [118]:
round_order = {
    '1st Round':1,
    '2nd Round':2, 
    'Quarterfinals':5,    
    'Semifinals': 6,
    'The Final': 7,     
    '3rd Round':3,     
    '4th Round':4,   
    'Round Robin':4
}

In [119]:
df.info()

<class 'pandas.DataFrame'>
Index: 41027 entries, 27525 to 68590
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tournament  41027 non-null  str
 1   Date        41027 non-null  datetime64[us]
 2   Series      41027 non-null  str
 3   Court       41027 non-null  str
 4   Surface     41027 non-null  str
 5   Round       41027 non-null  str
 6   Best of     41027 non-null  int64
 7   Player_1    41027 non-null  str
 8   Player_2    41027 non-null  str
 9   Winner      41027 non-null  str
 10  Rank_1      41027 non-null  float64
 11  Rank_2      41027 non-null  float64
 12  Pts_1       41027 non-null  float64
 13  Pts_2       41027 non-null  float64
 14  Odd_1       41027 non-null  float64
 15  Odd_2       41027 non-null  float64
 16  Score       41027 non-null  str
dtypes: datetime64[us](1), float64(6), int64(1), str(9)
memory usage: 5.6 MB

In [120]:
df["Round"] = df["Round"].str.strip().map(round_order)
df["Round"]

27525    1
27526    1
27527    1
27528    1
27529    1
        ..
68586    5
68587    5
68588    6
68589    6
68590    7
Name: Round, Length: 41027, dtype: int64

In [121]:
df["Round"].unique()

array([1, 2, 5, 6, 7, 3, 4])